In [1]:
import cv2 
import numpy as np 


In [7]:
img = cv2.imread('OpenRectangle.png',0)
edges = cv2.Canny(img,75,150)
lines = cv2.HoughLinesP(edges,1,np.pi/180,30,maxLineGap=250)



In [8]:
for line in lines:
    print(line)
    x1 , y1 , x2 , y2 = line[0]
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

[[228 158 707 158]]
[[225 164 707 164]]
[[225 394 707 394]]
[[225 388 707 388]]
[[707 393 707 159]]
[[702 395 702 165]]
[[225 389 708 389]]
[[225 393 225 161]]
[[230 395 230 167]]
[[231 395 231 165]]
[[585 395 703 395]]


In [9]:
cv2.imshow('Edges',edges)
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()